# Generated by Django 2.1.7 on 2019-03-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_zipdist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipDist_2digits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_country_2digits', models.CharField(max_length=4)),
                ('b_country_2digits', models.CharField(max_length=4)),
                ('distance_fly', models.FloatField()),
                ('distance_route', models.FloatField()),
            ],
        ),
    ]
