# Generated by Django 2.1.4 on 2019-01-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
